In this stage, you'll implement the =cd= builtin to handle absolute
paths.

*** The =cd= Builtin
:PROPERTIES:
:CUSTOM_ID: the-cd-builtin
:END:
The =cd= (change directory) builtin is used to change the current
working directory.

The =cd= command can handle different types of arguments:

- Absolute paths, like =/usr/local/bin=.
- Relative paths, like =./=, =../=, =./dir=.
- The =~= character, which represents the user's home directory.

For this stage, we'll focus on absolute paths.

*** Handling Absolute Paths
:PROPERTIES:
:CUSTOM_ID: handling-absolute-paths
:END:
An absolute path starts with =/= and specifies a location from the root
of the filesystem.

When =cd= receives an absolute path: - If the directory exists, change
to that directory. - If the directory doesn't exist, print
=cd: <directory>: No such file or directory=.

For example:

#+begin_src sh
$ pwd
/home/user
$ cd /usr/local/bin
$ pwd
/usr/local/bin
$ cd /does_not_exist
cd: /does_not_exist: No such file or directory
$ pwd
/usr/local/bin
#+end_src

If the directory change fails, the current directory should remain
unchanged.

*** Tests
:PROPERTIES:
:CUSTOM_ID: tests
:END:
The tester will execute your program like this:

#+begin_src sh
./your_program.sh
#+end_src

It will then send a series of =cd= commands to your shell:

#+begin_src sh
$ cd /usr/local/bin
$ pwd
/usr/local/bin
$ cd /does_not_exist
cd: /does_not_exist: No such file or directory
$
#+end_src

The tester will verify that: - Valid paths change the directory. -
Invalid paths print the error message
=cd: <directory>: No such file or directory=. - Invalid paths don't
change the current directory.

*** Notes
:PROPERTIES:
:CUSTOM_ID: notes
:END:
- Check if the directory exists before attempting to change to it, or
  handle the error if the change fails.
