In this stage, you'll extend your shell's tab completion to include
external executable files in the user's =PATH=.

*** Tab Completion for Executables
:PROPERTIES:
:CUSTOM_ID: tab-completion-for-executables
:END:
In previous stages, you implemented tab completion for builtin commands
(=echo= and =exit=). Now you'll extend completion to include external
executables found in the PATH environment variable.

When the user types the beginning of an executable's name and presses
=<TAB>=, your shell should complete it to the full executable name.

For example, if =custom_executable= exists in a directory listed in
PATH, typing =custom= and pressing tab completes to =custom_executable=
(with a trailing space).

*** Tests
:PROPERTIES:
:CUSTOM_ID: tests
:END:
The tester will create an executable file named =custom_executable= and
add its directory to the =PATH=.

It will then execute your program like this:

#+begin_src sh
./your_program.sh
#+end_src

Next, the tester will simulate a user typing the start of the external
command and pressing =<TAB>=:

#+begin_src sh
$ custom<TAB>
$ custom_executable 
#+end_src

The tester will verify that your shell correctly completes the command
to the external executable file name.

*** Notes
:PROPERTIES:
:CUSTOM_ID: notes
:END:
- PATH can include directories that don't exist on disk, so your code
  should handle such cases gracefully.
